# Generated by Django 5.2.3 on 2025-06-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="manufacturer",
        ),
    ]
