# Generated by Django 5.2.3 on 2025-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_pharmacyprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacyprofile",
            name="address",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("ADMIN", "Admin"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
    ]
